---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  annotations:
    prometheus.io/scrape: 'true'
    openyurt.io/topologyKeys: openyurt.io/nodepool
  labels:
    system.name: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: sock-shop-port
    port: 80
    targetPort: 8080
  - name: optl-port
    port: 9464
    targetPort: 9464
  selector:
    app: catalogue
