apiVersion: apps.openyurt.io/v1alpha1
kind: YurtAppSet
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  workloadTemplate:
    deploymentTemplate:
      metadata:
        labels:
          app: payment
      spec:
        template:
          metadata:
            labels:
              app: payment
          spec:
            containers:
            - name: server
              #image: weaveworksdemos/payment:0.4.3
              image: yidaoada/payment:v1.9
              resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
              - containerPort: 8080
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
                readOnlyRootFilesystem: true
            nodeSelector:
              beta.kubernetes.io/os: linux
              node-role.kubernetes.io/worker: ""
  topology:
    pools:
    - name: cloud
      nodeSelectorTerm:
        matchExpressions:
        - key: apps.openyurt.io/nodepool
          operator: In
          values:
          - cloud
      replicas: 1
    - name: edge
      nodeSelectorTerm:
        matchExpressions:
        - key: apps.openyurt.io/nodepool
          operator: In
          values:
          - edge-2
      replicas: 0


