apiVersion: apps.openyurt.io/v1alpha1
kind: YurtAppSet
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: shipping
spec:
  selector:
    matchLabels:
      app: shipping
  workloadTemplate:
    deploymentTemplate:
      metadata:
        labels:
          app: shipping
      spec:
        template:
          metadata:
            labels:
              app: shipping
          spec:
            containers:
            - name: server
              image: yidaoada/shipping-with-optl:v2.1
              env:
              - name: ZIPKIN
                value: zipkin.jaeger.svc.cluster.local
              - name: JAVA_OPTS
                value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
              resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 150Mi
              ports:
              - containerPort: 8082
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
                readOnlyRootFilesystem: true
              volumeMounts:
              - mountPath: /tmp
                name: tmp-volume
            volumes:
              - name: tmp-volume
                emptyDir:
                  medium: Memory
            nodeSelector:
              beta.kubernetes.io/os: linux
              node-role.kubernetes.io/worker: ""
  topology:
    pools:
    - name: cloud
      nodeSelectorTerm:
        matchExpressions:
        - key: apps.openyurt.io/nodepool
          operator: In
          values:
          - cloud
      replicas: 1
    - name: edge
      nodeSelectorTerm:
        matchExpressions:
        - key: apps.openyurt.io/nodepool
          operator: In
          values:
          - edge-2
      replicas: 0