apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-gateway-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: edge-gateway-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: edge-gateway-svc
    spec:
      containers:
      - image: habor.production.horsecoder.com/horsecoder/edge-gateway:latest
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 31808
          protocol: TCP
        - containerPort: 5005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        openyurt.io/is-edge-worker: "false"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30