apiVersion: v1
kind: Service
metadata:
  name: edge-paraformer-serverless-svc
spec:
  ports:
  - name: edge-paraformer-serverless-svc-5005
    port: 5005
    protocol: TCP
    targetPort: 5005
  - name: edge-paraformer-serverless-svc-12225
    port: 12225
    protocol: TCP
    targetPort: 12225
  - name: edge-paraformer-serverless-svc-12226
    port: 12226
    protocol: TCP
    targetPort: 12226
  selector:
    app: edge-paraformer-serverless-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}