apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-10T08:41:25Z"
  labels:
    v1.min.io/tenant: myminio
  name: myminio-nodeport
  namespace: horsecoder-minio
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: myminio
    uid: 1c32847e-a4bc-49aa-bed0-a60d1b017d97
  resourceVersion: "4646245"
  uid: 7b06dd92-923e-4fa3-802d-bc6002c2b766
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-minio
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 31190
  selector:
    v1.min.io/tenant: myminio
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
