apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data3-myminio-pool-0-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 60Gi