---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    system.name: sock-shop
  namespace: sock-shop
spec:
  type: NodePort
  ports:
  - name: sock-shop-port
    port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
