---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    tag: db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: sock-shop-port
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
