apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nacos
  name: data-nacos-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 20Gi