cat <<EOF | kubectl delete -f -
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  duration: '6m'
  selector:
    namespaces:
      - 'bookinfo'
    labelSelectors:
      'app': 'productpage'
EOF