apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-3
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - 'cloud-sock-shop'
    labelSelectors:
      'app': 'carts'
      'apps.openyurt.io/pool-name': cloud
  stressors:
    memory:
      workers: 1
      size: '100%'
  duration: '3m'