apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - 'cloud-sock-shop'
    labelSelectors:
      'app': 'shipping'
      'apps.openyurt.io/pool-name': edge
  stressors:
    cpu:
      workers: 2
      load: 100
  duration: '3m'