apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    pods:
      bookinfo:
        - details-v1-edge-2-558f5757fc-5l5r9
  stressors:
    cpu:
      workers: 2
      load: 100
  duration: '3m'