apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-3
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    pods:
      bookinfo:
        - details-v1-5c6887cb89-kfhs5
  stressors:
    memory:
      workers: 1
      size: '100%'
  duration: '3m'