apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-2
spec:
  action: delay
  mode: one
  selector:
    pods:
      bookinfo:
        - details-v1-5c6887cb89-kfhs5
  delay:
    latency: '1000ms'
    correlation: '100'
    jitter: '0ms'
  duration: '3m'