apiVersion: v1
kind: Service
metadata:
  name: nacos-svc
  namespace: nacos
  labels:
    app: nacos
spec:
  ports:
  - name: server
    port: 8848
    targetPort: 8848
    nodePort: 31848
  type: NodePort
  selector:
    app: nacos